---
output: 
  pdf_document:
    template: template.tex
---

\section{Keeping R tidy}

[Metro Bike Share](https://bikeshare.metro.net/) is a bike sharing system that operates in Los Angeles. Metro has been administering this bike share system since July 7, 2016. The way it works is riders can pick up a bike from one of the bike stations, ride it, and return it to a bike station. Make sure to read their homepage for more information about how the pricing works. 

Metro provides data on bike rides https://bikeshare.metro.net/about/data/. We will be using the data from the third quarter of 2019. Complete the following tasks based on this data.

1. Download the dataset and read it into R.

2. Check how many variables, and how many observations the dataset has. What does each row represent in the data?

3. Can you calculate how much money riders have paid to Metro in third quarter of 2019? If yes, calculate the value, if not explain why it cannot be calculated.

4. If you look into `passholder_type` closely, you will realize that some of the rides were test rides. Eliminate any ride that was a test ride from the dataset. 

5. There are three types of bike used in the Metro bike system as standard, electric, and smart. We want to make a comparison of standard bikes and the other two types. Make a new variable called standard. This variable should have "yes" values for bikes that are standard and "no" values for bikes that are electric or smart.

6. Calculate the mean, median, and sd of duration for standard and nonstandard bike rides. Calculate the number of standard and nonstandard bike rides.

7. Calculate the proportion of standard and nonstandard bike rides.