---
output: 
  pdf_document:
    template: template.tex
---

\section{library(bayesrules)}

- Download the package from https://github.com/mdogucu/bayesrules

- Can you locate what functions this package has based on the github repo? 

- Try using these functions with some alpha and beta values.

__Bechdel Test__

Alison Bechdel’s 1985 comic Dykes to Watch Out For has a strip called The Rule where a person states that they only go to a movie if it satisfies the
following three rules:
- the movie has to have at least two women in it;
- these two women talk to each other; and
- they talk about something besides a man.

This test is used for assessing movies in terms of representation of women. Even though there are three criteria, a movie either fails or passes the Bechdel test.

\section{Different priors, different posteriors}

Let $\pi$ be the the proportion of movies that pass the Bechdel test.

Below there are three different people with three different priors about $\pi$

\begin{center}
\begin{tabular}{ |c|c|c| } 
 \hline
 optimist & clueless & feminist \\ \hline
 Beta(14,1) & Beta(1,1) & Beta(5,11) \\ 
 \hline
\end{tabular}
\end{center}

1) Plot their priors.

__Informative prior:__ An informative prior reflects specific information about the unknown
variable with high certainty (ie. low variability).


__Vague (diffuse) prior:__

A vague or diffuse prior reflects little specific information about the unknown variable. A flat prior, which assigns equal prior plausibility to all possible values of the variable, is a special case.


2) `library(fivethirtyeight)` has `bechdel` data frame. Randomly select 20 movies from this dataset (seed = 84735)

3) Based on observed data, update the posterior for all three people. Write the distribution of the posterior.

4) Calculate the summary statistics for the prior and the posterior for all three.

5) Plot the prior, likelihood, and the posterior for all three.

6) Explain the effect of different priors on the posterior.

\newpage

\section{Different data, different posteriors}

Morteza, Nadide, and Ursula –  all share the optimistic Beta(14,1) prior for $\pi$ but each have access to different data. Morteza reviews movies from 1991. Nadidde reviews movies from 2000 and Ursula reviews movies from 2013. Repeat steps 1 through 6 on the previous page for Morteza, Nadide, and Ursula.

\section{Sequential Bayes}

Consider two new analysts Paola and Mark. Paola starts with Beta(14,1) prior. She first reviews movies from 1971 and updates her belief. Then reviews movies from 1972 and updates her belief. Then reviews movies from 1973 and updates her belief. Make sure to calculate the prior and posterior distribution at each point.

Mark also starts with Beta(14,1) prior. However he reviews movies from 1971, 1972, 1973 all at once. Calculate the posterior.

\section{Data order invariance}