---
title: "Beta Prior"
author: "Dr. Dogucu"
date: "2020-01-13"
output: 
  xaringan::moon_reader:
    css: slide-styles.css
      
---

layout: true
  
<div class="my-header"></div>

<div class="my-footer"> 
 Copyright &copy; <a href="https://mdogucu.ics.uci.edu">Dr. Mine Dogucu</a>. All Rights Reserved.</div> 

---

## Announcements

- Office Hours conflict?

- Tone on Piazza

- Wednesday discussion: R (tidyverse) review

---

## Review 

Let proportion of women in the U.S. who develop breast cancer in their lifetime be $\pi$. Even though $\pi$ can take any value between 0 and 1, for the purposes of this question, we will assume possible values of $\pi$ as 0.05, 0.10, 0.30, and 0.50. Since we do not have any medical doctors in our class, we will pretend that we do not have any specific prior ideas about breast cancer and choose a uniform prior. 

<table>
<tr>
  <th></th>
  <th> &Pi;</th>
  <th> 0.05</th>
  <th> 0.10</th>
  <th> 0.30</th>
  <th> 0.50</th>


</tr>

<tr>
  <td></td>
  <td> f(&Pi;)</td>
  <td> 0.25</td>
  <td> 0.25</td>
  <td> 0.25</td>
  <td> 0.25</td>

</tr>

</table>

We look at medical records of 8 women who have passed and 1 of them had developed breast cancer at some point in their life. Calculate the posterior distribution for $\pi$.

---
---
---
---

## Continuous Prior

We have been pretending that $\pi$ has few possible values but we know that it can take values between 0 and 1. Now it is time to consider all possible values of $\pi$. 

---

## Continuous Probability Models

Let $\pi$ be a continuous random variable with pdf $f(\pi)$.
Then $f(\pi)$ has the following properties:    

- $\int_\pi f(\pi)d\pi = 1$, ie. the area under $f(\pi)$ is 1
- $f(\pi) \ge 0$
- $P(a < \pi < b) = \int_a^b f(\pi) d\pi$ when $a \le b$

---
## Back to Graduate School Applications

Last lecture we were trying to understand $\pi$ the acceptance rate of a graduate program in a specific department. Let's make a fresh start to the same problem. This time we will let $\pi \in [0,1]$. 

---
## Plotting the continuous prior

For each of the student's prior ideas for $\pi$ plot the pdf of the prior. Your plot will not be exact since no exact values are given.  

Morteza thinks that it is extremely difficult to get into this program.

Jared thinks that it is difficult to get into this program. 

Erin does not have any strong opinions whether it is difficult or easy to get into this program. 

Xuan thinks that it is easy to get into this program.

Beyoncé thinks that it is extremely easy to get into this program.

---

## Beta Prior model

Let $\pi$ be a random variable which can take any value between 0 and 1, ie. $\pi \in [0,1]$.
Then the variability in $\pi$ might be well modeled by a Beta model with __shape parameters__ $\alpha > 0$ and $\beta > 0$: 

$$\pi \sim \text{Beta}(\alpha, \beta)$$
The Beta model is specified by continuous pdf
\begin{equation}
f(\pi) = \frac{\Gamma(\alpha + \beta)}{\Gamma(\alpha)\Gamma(\beta)} \pi^{\alpha-1} (1-\pi)^{\beta-1} \;\; \text{ for } \pi \in [0,1] 
\end{equation}
 where $\Gamma(z) = \int_0^\infty x^{z-1}e^{-x}dx$ and $\Gamma(z + 1) = z \Gamma(z)$.  Fun fact: when $z$ is a positive integer, then $\Gamma(z)$ simplifies to $\Gamma(z) = (z-1)!$.   
---
## Plotting Beta Prior


---
## Plotting Beta Prior

```{r echo = FALSE, message = FALSE, fig.align='center'}
library(tidyverse)
# Set up beta data
alpha <- c(1,1,3,1,5,20,7,2,5)
beta  <- c(5,2,7,1,5,20,3,1,1)
betas <- data.frame(setting = factor(rep(1:9, 
                                         each = 500)), 
                    x = rep(seq(0, 1, 
                                length = 500), 9),
                    alpha = rep(alpha, each = 500),
                    beta = rep(beta, each = 500))

betas <- betas %>% 
  mutate(y = dbeta(x, shape1 = alpha, shape2 = beta))

levels(betas$setting) <-
  paste0("Beta(",alpha,",",beta,")")

trend_data <- data.frame(alpha, beta,
                         means = (alpha / (alpha +
                                             beta)),
                         modes = 
                           ((alpha - 1) / 
                              (alpha + beta - 2))) %>% 
  mutate(Parameter = 
           paste0("Beta(",alpha,",",beta,")")) %>% 
  mutate(setting = Parameter) %>% 
  mutate(means_d = dbeta(means, alpha, beta), 
         modes_d = dbeta(modes, alpha, beta))

trend_data$setting <- factor(trend_data$setting, 
                             levels = c("Beta(1,5)",
                                        "Beta(1,2)",
                                        "Beta(3,7)",
                                        "Beta(1,1)",
                                        "Beta(5,5)",
                                        "Beta(20,20)",
                                        "Beta(7,3)",
                                        "Beta(2,1)",
                                        "Beta(5,1)"))
  
ggplot(betas, aes(x = x, y = y)) + 
  lims(x = c(0,1), y = c(0,5.5)) + 
  geom_line() + 
  facet_wrap(~ setting) + 
  labs(x = expression(pi), y =
         expression(paste("f(",pi,")"))) + 
  scale_x_continuous(breaks = c(0,0.25,0.5,0.75,1),
                     labels =
                       c("0","0.25","0.50","0.75","1")) +
  theme(text = element_text(size=20)) 

```

---

## Beta Descriptives

$E(\pi) = \frac{\alpha}{\alpha + \beta}$

$\text{Mode}(\pi) = \frac{\alpha - 1}{\alpha + \beta - 2}$  

$\text{Var}(\pi) = \frac{\alpha \beta}{(\alpha + \beta)^2(\alpha + \beta + 1)}$

---

Calculate the prior expected value, variance, and mode of $\pi$ that has a prior distribution of $Beta(1,2)$